# Extend the original image
FROM ghcr.io/danny-avila/librechat-dev:latest
USER root
# Install Python and pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3-dev py3-pip && ln -sf python3 /usr/bin/python
# RUN python3 -m ensurepip    
RUN pip3 install --no-cache --upgrade  --break-system-packages pip setuptools mcp
# Install the `mcp` package using pip
# RUN apk addmcp 