FROM ghcr.io/danny-avila/librechat-dev:latest
ENV HOST=0.0.0.0
ENV MONGO_URI=mongodb://mongodb:27017/LibreChat
ENV MEILI_HOST=http://meilisearch:7700
ENV RAG_PORT=${RAG_PORT:-8000}
ENV RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
USER root
# Install Python and pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3-dev py3-pip && ln -sf python3 /usr/bin/python
# RUN python3 -m ensurepip    
RUN pip3 install --no-cache --upgrade  --break-system-packages pip setuptools mcp